function Pull() {
    Cloth($.ajax);
    //Bar($.ajax);

}


function Cloth(ajaxFn) {
    //Cloth    
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_CLOTH,T3_CLOTH,T4_CLOTH,T5_CLOTH,T6_CLOTH,T7_CLOTH,T8_CLOTH,T4_CLOTH_LEVEL1@1,T5_CLOTH_LEVEL1@1,T6_CLOTH_LEVEL1@1,T7_CLOTH_LEVEL1@1,T8_CLOTH_LEVEL1@1,T4_CLOTH_LEVEL2@2,T5_CLOTH_LEVEL2@2,T6_CLOTH_LEVEL2@2,T7_CLOTH_LEVEL2@2,T8_CLOTH_LEVEL2@2,T4_CLOTH_LEVEL3@3,T5_CLOTH_LEVEL3@3,T6_CLOTH_LEVEL3@3,T7_CLOTH_LEVEL3@3,T8_CLOTH_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Cloth').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })
    //Metal Bar
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_METALBAR,T3_METALBAR,T4_METALBAR,T5_METALBAR,T6_METALBAR,T7_METALBAR,T8_METALBAR,T4_METALBAR_LEVEL1@1,T5_METALBAR_LEVEL1@1,T6_METALBAR_LEVEL1@1,T7_METALBAR_LEVEL1@1,T8_METALBAR_LEVEL1@1,T4_METALBAR_LEVEL2@2,T5_METALBAR_LEVEL2@2,T6_METALBAR_LEVEL2@2,T7_METALBAR_LEVEL2@2,T8_METALBAR_LEVEL2@2,T4_METALBAR_LEVEL3@3,T5_METALBAR_LEVEL3@3,T6_METALBAR_LEVEL3@3,T7_METALBAR_LEVEL3@3,T8_METALBAR_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Bars').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })
    //Leather
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_LEATHER,T3_LEATHER,T4_LEATHER,T5_LEATHER,T6_LEATHER,T7_LEATHER,T8_LEATHER,T4_LEATHER_LEVEL1@1,T5_LEATHER_LEVEL1@1,T6_LEATHER_LEVEL1@1,T7_LEATHER_LEVEL1@1,T8_LEATHER_LEVEL1@1,T4_LEATHER_LEVEL2@2,T5_LEATHER_LEVEL2@2,T6_LEATHER_LEVEL2@2,T7_LEATHER_LEVEL2@2,T8_LEATHER_LEVEL2@2,T4_LEATHER_LEVEL3@3,T5_LEATHER_LEVEL3@3,T6_LEATHER_LEVEL3@3,T7_LEATHER_LEVEL3@3,T8_LEATHER_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Leather').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })
    //Planks
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_PLANKS,T3_PLANKS,T4_PLANKS,T5_PLANKS,T6_PLANKS,T7_PLANKS,T8_PLANKS,T4_PLANKS_LEVEL1@1,T5_PLANKS_LEVEL1@1,T6_PLANKS_LEVEL1@1,T7_PLANKS_LEVEL1@1,T8_PLANKS_LEVEL1@1,T4_PLANKS_LEVEL2@2,T5_PLANKS_LEVEL2@2,T6_PLANKS_LEVEL2@2,T7_PLANKS_LEVEL2@2,T8_PLANKS_LEVEL2@2,T4_PLANKS_LEVEL3@3,T5_PLANKS_LEVEL3@3,T6_PLANKS_LEVEL3@3,T7_PLANKS_LEVEL3@3,T8_PLANKS_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Planks').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })
    //Fiber
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_FIBER,T3_FIBER,T4_FIBER,T5_FIBER,T6_FIBER,T7_FIBER,T8_FIBER,T4_FIBER_LEVEL1@1,T5_FIBER_LEVEL1@1,T6_FIBER_LEVEL1@1,T7_FIBER_LEVEL1@1,T8_FIBER_LEVEL1@1,T4_FIBER_LEVEL2@2,T5_FIBER_LEVEL2@2,T6_FIBER_LEVEL2@2,T7_FIBER_LEVEL2@2,T8_FIBER_LEVEL2@2,T4_FIBER_LEVEL3@3,T5_FIBER_LEVEL3@3,T6_FIBER_LEVEL3@3,T7_FIBER_LEVEL3@3,T8_FIBER_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Fiber').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })
    //Ore
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_ORE,T3_ORE,T4_ORE,T5_ORE,T6_ORE,T7_ORE,T8_ORE,T4_ORE_LEVEL1@1,T5_ORE_LEVEL1@1,T6_ORE_LEVEL1@1,T7_ORE_LEVEL1@1,T8_ORE_LEVEL1@1,T4_ORE_LEVEL2@2,T5_ORE_LEVEL2@2,T6_ORE_LEVEL2@2,T7_ORE_LEVEL2@2,T8_ORE_LEVEL2@2,T4_ORE_LEVEL3@3,T5_ORE_LEVEL3@3,T6_ORE_LEVEL3@3,T7_ORE_LEVEL3@3,T8_ORE_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Ores').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })
    //Logs
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_WOOD,T3_WOOD,T4_WOOD,T5_WOOD,T6_WOOD,T7_WOOD,T8_WOOD,T4_WOOD_LEVEL1@1,T5_WOOD_LEVEL1@1,T6_WOOD_LEVEL1@1,T7_WOOD_LEVEL1@1,T8_WOOD_LEVEL1@1,T4_WOOD_LEVEL2@2,T5_WOOD_LEVEL2@2,T6_WOOD_LEVEL2@2,T7_WOOD_LEVEL2@2,T8_WOOD_LEVEL2@2,T4_WOOD_LEVEL3@3,T5_WOOD_LEVEL3@3,T6_WOOD_LEVEL3@3,T7_WOOD_LEVEL3@3,T8_WOOD_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Logs').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })
    //Hides
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T2_HIDE,T3_HIDE,T4_HIDE,T5_HIDE,T6_HIDE,T7_HIDE,T8_HIDE,T4_HIDE_LEVEL1@1,T5_HIDE_LEVEL1@1,T6_HIDE_LEVEL1@1,T7_HIDE_LEVEL1@1,T8_HIDE_LEVEL1@1,T4_HIDE_LEVEL2@2,T5_HIDE_LEVEL2@2,T6_HIDE_LEVEL2@2,T7_HIDE_LEVEL2@2,T8_HIDE_LEVEL2@2,T4_HIDE_LEVEL3@3,T5_HIDE_LEVEL3@3,T6_HIDE_LEVEL3@3,T7_HIDE_LEVEL3@3,T8_HIDE_LEVEL3@3",
        success: function (data) {
            // render 
            for (i = 0; i < data.length; i++) {
                if (data[i].city == "Martlock") {
                    $('#Hides').append(`
                <tr>
                    <td>${data[i].item_id}</td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })

    //T4 Artifacts
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T4_ARTEFACT_2H_ARCANESTAFF_HELL,T4_ARTEFACT_2H_BOW_HELL,T4_ARTEFACT_2H_BOW_KEEPER,T4_ARTEFACT_2H_CLEAVER_HELL,T4_ARTEFACT_2H_COMBATSTAFF_MORGANA,T4_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T4_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T4_ARTEFACT_2H_DUALAXE_KEEPER,T4_ARTEFACT_2H_DUALCROSSBOW_HELL,T4_ARTEFACT_2H_DUALHAMMER_HELL,T4_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T4_ARTEFACT_2H_DUALSICKLE_UNDEAD,T4_ARTEFACT_2H_ENIGMATICORB_MORGANA,T4_ARTEFACT_2H_FIRESTAFF_HELL,T4_ARTEFACT_2H_HALBERD_MORGANA,T4_ARTEFACT_2H_HAMMER_UNDEAD,T4_ARTEFACT_2H_HARPOON_HELL,T4_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T4_ARTEFACT_2H_HOLYSTAFF_HELL,T4_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T4_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T4_ARTEFACT_2H_ICEGAUNTLETS_HELL,T4_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T4_ARTEFACT_2H_IRONGAUNTLETS_HELL,T4_ARTEFACT_2H_LONGBOW_UNDEAD,T4_ARTEFACT_2H_MACE_MORGANA,T4_ARTEFACT_2H_NATURESTAFF_HELL,T4_ARTEFACT_2H_NATURESTAFF_KEEPER,T4_ARTEFACT_2H_RAM_KEEPER,T4_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T4_ARTEFACT_2H_ROCKSTAFF_KEEPER,T4_ARTEFACT_2H_SKULLORB_HELL,T4_ARTEFACT_2H_TRIDENT_UNDEAD,T4_ARTEFACT_2H_TWINSCYTHE_HELL,T4_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T4_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T4_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T4_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T4_ARTEFACT_MAIN_MACE_HELL,T4_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T4_ARTEFACT_MAIN_RAPIER_MORGANA,T4_ARTEFACT_MAIN_ROCKMACE_KEEPER,T4_ARTEFACT_MAIN_SCIMITAR_MORGANA,T4_ARTEFACT_MAIN_SPEAR_KEEPER,T4_ARTEFACT_2H_SCYTHE_HELL,T4_ARTEFACT_OFF_TOWERSHIELD_UNDEAD,T4_ARTEFACT_OFF_SHIELD_HELL,T4_ARTEFACT_OFF_SPIKEDSHIELD_MORGANA,T4_ARTEFACT_OFF_ORB_MORGANA,T4_ARTEFACT_OFF_DEMONSKULL_HELL,T4_ARTEFACT_OFF_TOTEM_KEEPER,T4_ARTEFACT_OFF_HORN_KEEPER,T4_ARTEFACT_OFF_JESTERCANE_HELL,T4_ARTEFACT_OFF_LAMP_UNDEAD,T4_ARTEFACT_HEAD_PLATE_UNDEAD,T4_ARTEFACT_ARMOR_PLATE_UNDEAD,T4_ARTEFACT_SHOES_PLATE_UNDEAD,T4_ARTEFACT_HEAD_PLATE_HELL,T4_ARTEFACT_ARMOR_PLATE_HELL,T4_ARTEFACT_SHOES_PLATE_HELL,T4_ARTEFACT_HEAD_PLATE_KEEPER,T4_ARTEFACT_ARMOR_PLATE_KEEPER,T4_ARTEFACT_SHOES_PLATE_KEEPER,T4_ARTEFACT_HEAD_PLATE_AVALON,T4_ARTEFACT_ARMOR_PLATE_AVALON,T4_ARTEFACT_SHOES_PLATE_AVALON,T4_ARTEFACT_HEAD_LEATHER_MORGANA,T4_ARTEFACT_ARMOR_LEATHER_MORGANA,T4_ARTEFACT_SHOES_LEATHER_MORGANA,T4_ARTEFACT_HEAD_LEATHER_HELL,T4_ARTEFACT_ARMOR_LEATHER_HELL,T4_ARTEFACT_SHOES_LEATHER_HELL,T4_ARTEFACT_HEAD_LEATHER_UNDEAD,T4_ARTEFACT_ARMOR_LEATHER_UNDEAD,T4_ARTEFACT_SHOES_LEATHER_UNDEAD,T4_ARTEFACT_HEAD_LEATHER_AVALON,T4_ARTEFACT_ARMOR_LEATHER_AVALON,T4_ARTEFACT_SHOES_LEATHER_AVALON,T4_ARTEFACT_HEAD_CLOTH_KEEPER,T4_ARTEFACT_ARMOR_CLOTH_KEEPER,T4_ARTEFACT_SHOES_CLOTH_KEEPER,T4_ARTEFACT_HEAD_CLOTH_HELL,T4_ARTEFACT_ARMOR_CLOTH_HELL,T4_ARTEFACT_SHOES_CLOTH_HELL,T4_ARTEFACT_HEAD_CLOTH_MORGANA,T4_ARTEFACT_ARMOR_CLOTH_MORGANA,T4_ARTEFACT_SHOES_CLOTH_MORGANA,T4_ARTEFACT_HEAD_CLOTH_AVALON,T4_ARTEFACT_ARMOR_CLOTH_AVALON,T4_ARTEFACT_SHOES_CLOTH_AVALON",
        success: function (data) {
            // render 
            console.log(data[1]);
            for (i = 0; i < data.length; i++) {
                var name = data[i].item_id
                if (data[i].city == "Martlock") {
                    $('#T4Articats').append(`
                <tr>
                    <td> ${name.substring(12)} </td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })

    //T5 Artifacts
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T5_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T5_ARTEFACT_2H_ARCANESTAFF_HELL,T5_ARTEFACT_2H_BOW_HELL,T5_ARTEFACT_2H_BOW_KEEPER,T5_ARTEFACT_2H_CLEAVER_HELL,T5_ARTEFACT_2H_COMBATSTAFF_MORGANA,T5_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T5_ARTEFACT_2H_DUALAXE_KEEPER,T5_ARTEFACT_2H_DUALCROSSBOW_HELL,T5_ARTEFACT_2H_DUALHAMMER_HELL,T5_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T5_ARTEFACT_2H_DUALSICKLE_UNDEAD,T5_ARTEFACT_2H_ENIGMATICORB_MORGANA,T5_ARTEFACT_2H_FIRESTAFF_HELL,T5_ARTEFACT_2H_HALBERD_MORGANA,T5_ARTEFACT_2H_HAMMER_UNDEAD,T5_ARTEFACT_2H_HARPOON_HELL,T5_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T5_ARTEFACT_2H_HOLYSTAFF_HELL,T5_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T5_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T5_ARTEFACT_2H_ICEGAUNTLETS_HELL,T5_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T5_ARTEFACT_2H_IRONGAUNTLETS_HELL,T5_ARTEFACT_2H_LONGBOW_UNDEAD,T5_ARTEFACT_2H_MACE_MORGANA,T5_ARTEFACT_2H_NATURESTAFF_HELL,T5_ARTEFACT_2H_NATURESTAFF_KEEPER,T5_ARTEFACT_2H_RAM_KEEPER,T5_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T5_ARTEFACT_2H_ROCKSTAFF_KEEPER,T5_ARTEFACT_2H_SCYTHE_HELL,T5_ARTEFACT_2H_SKULLORB_HELL,T5_ARTEFACT_2H_TRIDENT_UNDEAD,T5_ARTEFACT_2H_TWINSCYTHE_HELL,T5_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T5_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T5_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T5_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T5_ARTEFACT_MAIN_MACE_HELL,T5_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T5_ARTEFACT_MAIN_RAPIER_MORGANA,T5_ARTEFACT_MAIN_ROCKMACE_KEEPER,T5_ARTEFACT_MAIN_SCIMITAR_MORGANA,T5_ARTEFACT_MAIN_SPEAR_KEEPER,T5_ARTEFACT_OFF_TOWERSHIELD_UNDEAD,T5_ARTEFACT_OFF_SHIELD_HELL,T5_ARTEFACT_OFF_SPIKEDSHIELD_MORGANA,T5_ARTEFACT_OFF_ORB_MORGANA,T5_ARTEFACT_OFF_DEMONSKULL_HELL,T5_ARTEFACT_OFF_TOTEM_KEEPER,T5_ARTEFACT_OFF_HORN_KEEPER,T5_ARTEFACT_OFF_JESTERCANE_HELL,T5_ARTEFACT_OFF_LAMP_UNDEAD,T5_ARTEFACT_HEAD_PLATE_UNDEAD,T5_ARTEFACT_ARMOR_PLATE_UNDEAD,T5_ARTEFACT_SHOES_PLATE_UNDEAD,T5_ARTEFACT_HEAD_PLATE_HELL,T5_ARTEFACT_ARMOR_PLATE_HELL,T5_ARTEFACT_SHOES_PLATE_HELL,T5_ARTEFACT_HEAD_PLATE_KEEPER,T5_ARTEFACT_ARMOR_PLATE_KEEPER,T5_ARTEFACT_SHOES_PLATE_KEEPER,T5_ARTEFACT_HEAD_PLATE_AVALON,T5_ARTEFACT_ARMOR_PLATE_AVALON,T5_ARTEFACT_SHOES_PLATE_AVALON,T5_ARTEFACT_HEAD_LEATHER_MORGANA,T5_ARTEFACT_ARMOR_LEATHER_MORGANA,T5_ARTEFACT_SHOES_LEATHER_MORGANA,T5_ARTEFACT_HEAD_LEATHER_HELL,T5_ARTEFACT_ARMOR_LEATHER_HELL,T5_ARTEFACT_SHOES_LEATHER_HELL,T5_ARTEFACT_HEAD_LEATHER_UNDEAD,T5_ARTEFACT_ARMOR_LEATHER_UNDEAD,T5_ARTEFACT_SHOES_LEATHER_UNDEAD,T5_ARTEFACT_HEAD_LEATHER_AVALON,T5_ARTEFACT_ARMOR_LEATHER_AVALON,T5_ARTEFACT_SHOES_LEATHER_AVALON,T5_ARTEFACT_HEAD_CLOTH_KEEPER,T5_ARTEFACT_ARMOR_CLOTH_KEEPER,T5_ARTEFACT_SHOES_CLOTH_KEEPER,T5_ARTEFACT_HEAD_CLOTH_HELL,T5_ARTEFACT_ARMOR_CLOTH_HELL,T5_ARTEFACT_SHOES_CLOTH_HELL,T5_ARTEFACT_HEAD_CLOTH_MORGANA,T5_ARTEFACT_ARMOR_CLOTH_MORGANA,T5_ARTEFACT_SHOES_CLOTH_MORGANA,T5_ARTEFACT_HEAD_CLOTH_AVALON,T5_ARTEFACT_ARMOR_CLOTH_AVALON,T5_ARTEFACT_SHOES_CLOTH_AVALON",
        success: function (data) {
            // render 
            console.log(data[1]);
            for (i = 0; i < data.length; i++) {
                var name = data[i].item_id
                if (data[i].city == "Martlock") {
                    $('#T5Articats').append(`
                <tr>
                    <td> ${name.substring(12)} </td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })

    //T6 Artifacts
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T6_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T6_ARTEFACT_2H_SCYTHE_HELL,T6_ARTEFACT_2H_ARCANESTAFF_HELL,T6_ARTEFACT_2H_BOW_HELL,T6_ARTEFACT_2H_BOW_KEEPER,T6_ARTEFACT_2H_CLEAVER_HELL,T6_ARTEFACT_2H_COMBATSTAFF_MORGANA,T6_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T6_ARTEFACT_2H_DUALAXE_KEEPER,T6_ARTEFACT_2H_DUALCROSSBOW_HELL,T6_ARTEFACT_2H_DUALHAMMER_HELL,T6_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T6_ARTEFACT_2H_DUALSICKLE_UNDEAD,T6_ARTEFACT_2H_ENIGMATICORB_MORGANA,T6_ARTEFACT_2H_FIRESTAFF_HELL,T6_ARTEFACT_2H_HALBERD_MORGANA,T6_ARTEFACT_2H_HAMMER_UNDEAD,T6_ARTEFACT_2H_HARPOON_HELL,T6_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T6_ARTEFACT_2H_HOLYSTAFF_HELL,T6_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T6_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T6_ARTEFACT_2H_ICEGAUNTLETS_HELL,T6_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T6_ARTEFACT_2H_IRONGAUNTLETS_HELL,T6_ARTEFACT_2H_LONGBOW_UNDEAD,T6_ARTEFACT_2H_MACE_MORGANA,T6_ARTEFACT_2H_NATURESTAFF_HELL,T6_ARTEFACT_2H_NATURESTAFF_KEEPER,T6_ARTEFACT_2H_RAM_KEEPER,T6_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T6_ARTEFACT_2H_ROCKSTAFF_KEEPER,T6_ARTEFACT_2H_SKULLORB_HELL,T6_ARTEFACT_2H_TRIDENT_UNDEAD,T6_ARTEFACT_2H_TWINSCYTHE_HELL,T6_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T6_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T6_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T6_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T6_ARTEFACT_MAIN_MACE_HELL,T6_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T6_ARTEFACT_MAIN_RAPIER_MORGANA,T6_ARTEFACT_MAIN_ROCKMACE_KEEPER,T6_ARTEFACT_MAIN_SCIMITAR_MORGANA,T6_ARTEFACT_MAIN_SPEAR_KEEPER,T6_ARTEFACT_OFF_TOWERSHIELD_UNDEAD,T6_ARTEFACT_OFF_SHIELD_HELL,T6_ARTEFACT_OFF_SPIKEDSHIELD_MORGANA,T6_ARTEFACT_OFF_ORB_MORGANA,T6_ARTEFACT_OFF_DEMONSKULL_HELL,T6_ARTEFACT_OFF_TOTEM_KEEPER,T6_ARTEFACT_OFF_HORN_KEEPER,T6_ARTEFACT_OFF_JESTERCANE_HELL,T6_ARTEFACT_OFF_LAMP_UNDEAD,T6_ARTEFACT_HEAD_PLATE_UNDEAD,T6_ARTEFACT_ARMOR_PLATE_UNDEAD,T6_ARTEFACT_SHOES_PLATE_UNDEAD,T6_ARTEFACT_HEAD_PLATE_HELL,T6_ARTEFACT_ARMOR_PLATE_HELL,T6_ARTEFACT_SHOES_PLATE_HELL,T6_ARTEFACT_HEAD_PLATE_KEEPER,T6_ARTEFACT_ARMOR_PLATE_KEEPER,T6_ARTEFACT_SHOES_PLATE_KEEPER,T6_ARTEFACT_HEAD_PLATE_AVALON,T6_ARTEFACT_ARMOR_PLATE_AVALON,T6_ARTEFACT_SHOES_PLATE_AVALON,T6_ARTEFACT_HEAD_LEATHER_MORGANA,T6_ARTEFACT_ARMOR_LEATHER_MORGANA,T6_ARTEFACT_SHOES_LEATHER_MORGANA,T6_ARTEFACT_HEAD_LEATHER_HELL,T6_ARTEFACT_ARMOR_LEATHER_HELL,T6_ARTEFACT_SHOES_LEATHER_HELL,T6_ARTEFACT_HEAD_LEATHER_UNDEAD,T6_ARTEFACT_ARMOR_LEATHER_UNDEAD,T6_ARTEFACT_SHOES_LEATHER_UNDEAD,T6_ARTEFACT_HEAD_LEATHER_AVALON,T6_ARTEFACT_ARMOR_LEATHER_AVALON,T6_ARTEFACT_SHOES_LEATHER_AVALON,T6_ARTEFACT_HEAD_CLOTH_KEEPER,T6_ARTEFACT_ARMOR_CLOTH_KEEPER,T6_ARTEFACT_SHOES_CLOTH_KEEPER,T6_ARTEFACT_HEAD_CLOTH_HELL,T6_ARTEFACT_ARMOR_CLOTH_HELL,T6_ARTEFACT_SHOES_CLOTH_HELL,T6_ARTEFACT_HEAD_CLOTH_MORGANA,T6_ARTEFACT_ARMOR_CLOTH_MORGANA,T6_ARTEFACT_SHOES_CLOTH_MORGANA,T6_ARTEFACT_HEAD_CLOTH_AVALON,T6_ARTEFACT_ARMOR_CLOTH_AVALON,T6_ARTEFACT_SHOES_CLOTH_AVALON",
        success: function (data) {
            // render 
            console.log(data[1]);
            for (i = 0; i < data.length; i++) {
                var name = data[i].item_id
                if (data[i].city == "Martlock") {
                    $('#T6Articats').append(`
                <tr>
                    <td> ${name.substring(12)} </td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })

    //T7 Artifacts
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T7_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T7_ARTEFACT_2H_SCYTHE_HELL,T7_ARTEFACT_2H_ARCANESTAFF_HELL,T7_ARTEFACT_2H_BOW_HELL,T7_ARTEFACT_2H_BOW_KEEPER,T7_ARTEFACT_2H_CLEAVER_HELL,T7_ARTEFACT_2H_COMBATSTAFF_MORGANA,T7_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T7_ARTEFACT_2H_DUALAXE_KEEPER,T7_ARTEFACT_2H_DUALCROSSBOW_HELL,T7_ARTEFACT_2H_DUALHAMMER_HELL,T7_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T7_ARTEFACT_2H_DUALSICKLE_UNDEAD,T7_ARTEFACT_2H_ENIGMATICORB_MORGANA,T7_ARTEFACT_2H_FIRESTAFF_HELL,T7_ARTEFACT_2H_HALBERD_MORGANA,T7_ARTEFACT_2H_HAMMER_UNDEAD,T7_ARTEFACT_2H_HARPOON_HELL,T7_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T7_ARTEFACT_2H_HOLYSTAFF_HELL,T7_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T7_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T7_ARTEFACT_2H_ICEGAUNTLETS_HELL,T7_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T7_ARTEFACT_2H_IRONGAUNTLETS_HELL,T7_ARTEFACT_2H_LONGBOW_UNDEAD,T7_ARTEFACT_2H_MACE_MORGANA,T7_ARTEFACT_2H_NATURESTAFF_HELL,T7_ARTEFACT_2H_NATURESTAFF_KEEPER,T7_ARTEFACT_2H_RAM_KEEPER,T7_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T7_ARTEFACT_2H_ROCKSTAFF_KEEPER,T7_ARTEFACT_2H_SKULLORB_HELL,T7_ARTEFACT_2H_TRIDENT_UNDEAD,T7_ARTEFACT_2H_TWINSCYTHE_HELL,T7_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T7_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T7_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T7_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T7_ARTEFACT_MAIN_MACE_HELL,T7_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T7_ARTEFACT_MAIN_RAPIER_MORGANA,T7_ARTEFACT_MAIN_ROCKMACE_KEEPER,T7_ARTEFACT_MAIN_SCIMITAR_MORGANA,T7_ARTEFACT_MAIN_SPEAR_KEEPER,T7_ARTEFACT_OFF_TOWERSHIELD_UNDEAD,T7_ARTEFACT_OFF_SHIELD_HELL,T7_ARTEFACT_OFF_SPIKEDSHIELD_MORGANA,T7_ARTEFACT_OFF_ORB_MORGANA,T7_ARTEFACT_OFF_DEMONSKULL_HELL,T7_ARTEFACT_OFF_TOTEM_KEEPER,T7_ARTEFACT_OFF_HORN_KEEPER,T7_ARTEFACT_OFF_JESTERCANE_HELL,T7_ARTEFACT_OFF_LAMP_UNDEAD,T7_ARTEFACT_HEAD_PLATE_UNDEAD,T7_ARTEFACT_ARMOR_PLATE_UNDEAD,T7_ARTEFACT_SHOES_PLATE_UNDEAD,T7_ARTEFACT_HEAD_PLATE_HELL,T7_ARTEFACT_ARMOR_PLATE_HELL,T7_ARTEFACT_SHOES_PLATE_HELL,T7_ARTEFACT_HEAD_PLATE_KEEPER,T7_ARTEFACT_ARMOR_PLATE_KEEPER,T7_ARTEFACT_SHOES_PLATE_KEEPER,T7_ARTEFACT_HEAD_PLATE_AVALON,T7_ARTEFACT_ARMOR_PLATE_AVALON,T7_ARTEFACT_SHOES_PLATE_AVALON,T7_ARTEFACT_HEAD_LEATHER_MORGANA,T7_ARTEFACT_ARMOR_LEATHER_MORGANA,T7_ARTEFACT_SHOES_LEATHER_MORGANA,T7_ARTEFACT_HEAD_LEATHER_HELL,T7_ARTEFACT_ARMOR_LEATHER_HELL,T7_ARTEFACT_SHOES_LEATHER_HELL,T7_ARTEFACT_HEAD_LEATHER_UNDEAD,T7_ARTEFACT_ARMOR_LEATHER_UNDEAD,T7_ARTEFACT_SHOES_LEATHER_UNDEAD,T7_ARTEFACT_HEAD_LEATHER_AVALON,T7_ARTEFACT_ARMOR_LEATHER_AVALON,T7_ARTEFACT_SHOES_LEATHER_AVALON,T7_ARTEFACT_HEAD_CLOTH_KEEPER,T7_ARTEFACT_ARMOR_CLOTH_KEEPER,T7_ARTEFACT_SHOES_CLOTH_KEEPER,T7_ARTEFACT_HEAD_CLOTH_HELL,T7_ARTEFACT_ARMOR_CLOTH_HELL,T7_ARTEFACT_SHOES_CLOTH_HELL,T7_ARTEFACT_HEAD_CLOTH_MORGANA,T7_ARTEFACT_ARMOR_CLOTH_MORGANA,T7_ARTEFACT_SHOES_CLOTH_MORGANA,T7_ARTEFACT_HEAD_CLOTH_AVALON,T7_ARTEFACT_ARMOR_CLOTH_AVALON,T7_ARTEFACT_SHOES_CLOTH_AVALON",
        success: function (data) {
            // render 
            console.log(data[1]);
            for (i = 0; i < data.length; i++) {
                var name = data[i].item_id
                if (data[i].city == "Martlock") {
                    $('#T7Articats').append(`
                <tr>
                    <td> ${name.substring(12)} </td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })

    //T8 Artifacts
    ajaxFn({
        url: "https://www.albion-online-data.com/api/v1/stats/prices/T8_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T8_ARTEFACT_2H_SCYTHE_HELL,T8_ARTEFACT_2H_ARCANESTAFF_HELL,T8_ARTEFACT_2H_BOW_HELL,T8_ARTEFACT_2H_BOW_KEEPER,T8_ARTEFACT_2H_CLEAVER_HELL,T8_ARTEFACT_2H_COMBATSTAFF_MORGANA,T8_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T8_ARTEFACT_2H_DUALAXE_KEEPER,T8_ARTEFACT_2H_DUALCROSSBOW_HELL,T8_ARTEFACT_2H_DUALHAMMER_HELL,T8_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T8_ARTEFACT_2H_DUALSICKLE_UNDEAD,T8_ARTEFACT_2H_ENIGMATICORB_MORGANA,T8_ARTEFACT_2H_FIRESTAFF_HELL,T8_ARTEFACT_2H_HALBERD_MORGANA,T8_ARTEFACT_2H_HAMMER_UNDEAD,T8_ARTEFACT_2H_HARPOON_HELL,T8_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T8_ARTEFACT_2H_HOLYSTAFF_HELL,T8_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T8_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T8_ARTEFACT_2H_ICEGAUNTLETS_HELL,T8_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T8_ARTEFACT_2H_IRONGAUNTLETS_HELL,T8_ARTEFACT_2H_LONGBOW_UNDEAD,T8_ARTEFACT_2H_MACE_MORGANA,T8_ARTEFACT_2H_NATURESTAFF_HELL,T8_ARTEFACT_2H_NATURESTAFF_KEEPER,T8_ARTEFACT_2H_RAM_KEEPER,T8_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T8_ARTEFACT_2H_ROCKSTAFF_KEEPER,T8_ARTEFACT_2H_SKULLORB_HELL,T8_ARTEFACT_2H_TRIDENT_UNDEAD,T8_ARTEFACT_2H_TWINSCYTHE_HELL,T8_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T8_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T8_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T8_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T8_ARTEFACT_MAIN_MACE_HELL,T8_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T8_ARTEFACT_MAIN_RAPIER_MORGANA,T8_ARTEFACT_MAIN_ROCKMACE_KEEPER,T8_ARTEFACT_MAIN_SCIMITAR_MORGANA,T8_ARTEFACT_MAIN_SPEAR_KEEPER,T8_ARTEFACT_OFF_TOWERSHIELD_UNDEAD,T8_ARTEFACT_OFF_SHIELD_HELL,T8_ARTEFACT_OFF_SPIKEDSHIELD_MORGANA,T8_ARTEFACT_OFF_ORB_MORGANA,T8_ARTEFACT_OFF_DEMONSKULL_HELL,T8_ARTEFACT_OFF_TOTEM_KEEPER,T8_ARTEFACT_OFF_HORN_KEEPER,T8_ARTEFACT_OFF_JESTERCANE_HELL,T8_ARTEFACT_OFF_LAMP_UNDEAD,T8_ARTEFACT_HEAD_PLATE_UNDEAD,T8_ARTEFACT_ARMOR_PLATE_UNDEAD,T8_ARTEFACT_SHOES_PLATE_UNDEAD,T8_ARTEFACT_HEAD_PLATE_HELL,T8_ARTEFACT_ARMOR_PLATE_HELL,T8_ARTEFACT_SHOES_PLATE_HELL,T8_ARTEFACT_HEAD_PLATE_KEEPER,T8_ARTEFACT_ARMOR_PLATE_KEEPER,T8_ARTEFACT_SHOES_PLATE_KEEPER,T8_ARTEFACT_HEAD_PLATE_AVALON,T8_ARTEFACT_ARMOR_PLATE_AVALON,T8_ARTEFACT_SHOES_PLATE_AVALON,T8_ARTEFACT_HEAD_LEATHER_MORGANA,T8_ARTEFACT_ARMOR_LEATHER_MORGANA,T8_ARTEFACT_SHOES_LEATHER_MORGANA,T8_ARTEFACT_HEAD_LEATHER_HELL,T8_ARTEFACT_ARMOR_LEATHER_HELL,T8_ARTEFACT_SHOES_LEATHER_HELL,T8_ARTEFACT_HEAD_LEATHER_UNDEAD,T8_ARTEFACT_ARMOR_LEATHER_UNDEAD,T8_ARTEFACT_SHOES_LEATHER_UNDEAD,T8_ARTEFACT_HEAD_LEATHER_AVALON,T8_ARTEFACT_ARMOR_LEATHER_AVALON,T8_ARTEFACT_SHOES_LEATHER_AVALON,T8_ARTEFACT_HEAD_CLOTH_KEEPER,T8_ARTEFACT_ARMOR_CLOTH_KEEPER,T8_ARTEFACT_SHOES_CLOTH_KEEPER,T8_ARTEFACT_HEAD_CLOTH_HELL,T8_ARTEFACT_ARMOR_CLOTH_HELL,T8_ARTEFACT_SHOES_CLOTH_HELL,T8_ARTEFACT_HEAD_CLOTH_MORGANA,T8_ARTEFACT_ARMOR_CLOTH_MORGANA,T8_ARTEFACT_SHOES_CLOTH_MORGANA,T8_ARTEFACT_HEAD_CLOTH_AVALON,T8_ARTEFACT_ARMOR_CLOTH_AVALON,T8_ARTEFACT_SHOES_CLOTH_AVALON",
        success: function (data) {
            // render 
            console.log(data[1]);
            for (i = 0; i < data.length; i++) {
                var name = data[i].item_id
                if (data[i].city == "Martlock") {
                    $('#T8Articats').append(`
                <tr>
                    <td> ${name.substring(12)} </td>
                    <td>${data[i].buy_price_max}</td>
                    <td>${data[i].sell_price_min}</td>
                </tr>`)
                }

            }

        }
    })



}



window.onload = Pull();